name: RaskolEnchant
version: ${project.version}
main: ru.raskol.enchant.RaskolEnchant
api-version: '1.21'
author: Baltimor
description: Кастомная система зачарований - книга 30%, осколок 1%, чертёж 100%.
commands:
  renchant:
    description: Управление зачарованиями
    usage: /renchant help
permissions:
  renchant.admin:
    description: Админ-команды зачарований
    default: op
